"""
ArxPrism Models Package
"""

from src.models.schemas import (
    APIResponse,
    PipelineTriggerRequest,
    PipelineTriggerResponse,
    PaperGraphNode,
    PaperGraphRelationship,
    PaperGraphResponse,
    EvolutionTreeNode,
    EvolutionTreeLink,
    EvolutionTreeResponse,
    PaperExtractionResponse,
    TriageResponse,
    ExtractionData,
    KnowledgeGraphNodes,
    ExperimentComparison,
    CriticalAnalysis,
    ProposedMethod,
    EntityCluster,
    EntityResolutionResponse,
)

from src.models.task_models import (
    TaskStatus,
    TaskProgress,
    Task,
    PaperProcessingStatus,
    PaperProcessingResult,
    TaskCreateRequest,
    TaskCreateResponse,
    TaskListResponse,
    TaskSummary,
    DomainPreset,
    DOMAIN_PRESETS,
    get_domain_preset,
    list_domain_presets,
)

__all__ = [
    # Schemas
    "APIResponse",
    "PipelineTriggerRequest",
    "PipelineTriggerResponse",
    "PaperGraphNode",
    "PaperGraphRelationship",
    "PaperGraphResponse",
    "EvolutionTreeNode",
    "EvolutionTreeLink",
    "EvolutionTreeResponse",
    "PaperExtractionResponse",
    "TriageResponse",
    "ExtractionData",
    "KnowledgeGraphNodes",
    "ExperimentComparison",
    "CriticalAnalysis",
    "ProposedMethod",
    "EntityCluster",
    "EntityResolutionResponse",
    # Task Models
    "TaskStatus",
    "TaskProgress",
    "Task",
    "PaperProcessingStatus",
    "PaperProcessingResult",
    "TaskCreateRequest",
    "TaskCreateResponse",
    "TaskListResponse",
    "TaskSummary",
    "DomainPreset",
    "DOMAIN_PRESETS",
    "get_domain_preset",
    "list_domain_presets",
]
